Desafio/force-app/main/default/objects/Case/fields/DataLimiteResolucao__c.field-meta.xml
<CustomField>
    <fullName>DataLimiteResolucao__c</fullName>
    <label>Data Limite Para Resolução</label>
    <type>DateTime</type>
</CustomField>

Desafio/force-app/main/default/objects/Case/fields/Urgencia__c.field-meta.xml
<CustomField>
    <fullName>Urgencia__c</fullName>
    <label>Urgência</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baixa</fullName>
                <default>true</default>
                <label>Baixa</label>
            </value>
            <value>
                <fullName>Média</fullName>
            </value>
            <value>
                <fullName>Alta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Desafio/force-app/main/default/objects/SLA__mdt/fields/MinutosParaResolucao__c.field-meta.xml
<CustomField>
    <fullName>MinutosParaResolucao__c</fullName>
    <label>Minutos para Resolução</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Desafio/force-app/main/default/objects/SLA__mdt/fields/Urgencia__c.field-meta.xml
<CustomField>
    <fullName>Urgencia__c</fullName>
    <label>Urgência</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Desafio/force-app/main/default/classes/CaseSLAHandler.cls
public class CaseSLAHandler {
    
    public static void handleSLACalculation(List<Case> newCases, Map<Id, Case> oldCaseMap, Boolean isInsert, Boolean isUpdate) {
        
        Map<String, Integer> slaMap = new Map<String, Integer>();        
        for (SLA__mdt sla : [SELECT Urgencia__c, MinutosParaResolucao__c FROM SLA__mdt]) {
            slaMap.put(sla.Urgencia__c, Integer.valueOf(sla.MinutosParaResolucao__c));
        }
        
        for (Case caso : newCases) {
            
            if (isInsert || 
                (isUpdate && caso.Urgencia__c != oldCaseMap.get(caso.Id).Urgencia__c)) {
                
                if (caso.Urgencia__c != null && slaMap.containsKey(caso.Urgencia__c)) {
                    Integer minutes = slaMap.get(caso.Urgencia__c);
                    caso.DataLimiteResolucao__c = DateTime.now().addMinutes(minutes);
                }
            }
        }
    }
}